function generateAllDetectionExamples()
    % Generate detection-example figures for all four provided data sets.

    fs = 2.4e6;
    fc = 134.8e6;
    t0 = 1.0;

    data_files = { ...
        'ab134.8_d1.mat', ...
        'ab134.8_d2.mat', ...
        'ab134.8_d3.mat', ...
        'ab134.8_d4.mat' ...
    };

    output_names = { ...
        'd1_detection_example.png', ...
        'd2_detection_example.png', ...
        'd3_detection_example.png', ...
        'd4_detection_example.png' ...
    };

    for i = 1:length(data_files)
        vars = load(data_files{i});
        fnames = fieldnames(vars);
        data = vars.(fnames{1});

        plotDetectionExample(data, fs, fc, t0, output_names{i});
        fprintf('Saved %s\n', fullfile('output', output_names{i}));
    end
end
